# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Main(object):
    def setupUi(self, Form_Main):
        Form_Main.setObjectName("Form_Main")
        Form_Main.resize(600, 504)
        Form_Main.setMinimumSize(QtCore.QSize(600, 500))
        Form_Main.setMaximumSize(QtCore.QSize(602, 504))
        Form_Main.setStyleSheet("QWidget{\n"
"background:rgb(42, 42, 42);\n"
"font: 75 italic 12pt \"Arial Narrow\";\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton{\n"
"background:rgb(0, 127, 21);\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form_Main)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form_Main)
        self.groupBox.setMinimumSize(QtCore.QSize(584, 486))
        self.groupBox.setMaximumSize(QtCore.QSize(584, 486))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_Venta = QtWidgets.QPushButton(self.frame)
        self.btn_Venta.setGeometry(QtCore.QRect(0, 50, 75, 23))
        self.btn_Venta.setObjectName("btn_Venta")
        self.btn_Producto = QtWidgets.QPushButton(self.frame)
        self.btn_Producto.setGeometry(QtCore.QRect(80, 50, 75, 23))
        self.btn_Producto.setObjectName("btn_Producto")
        self.btn_Cuenta = QtWidgets.QPushButton(self.frame)
        self.btn_Cuenta.setGeometry(QtCore.QRect(170, 50, 75, 23))
        self.btn_Cuenta.setObjectName("btn_Cuenta")
        self.btn_Gasto = QtWidgets.QPushButton(self.frame)
        self.btn_Gasto.setGeometry(QtCore.QRect(260, 50, 75, 23))
        self.btn_Gasto.setObjectName("btn_Gasto")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(370, 420, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_Dinero = QtWidgets.QLabel(self.frame)
        self.label_Dinero.setGeometry(QtCore.QRect(490, 420, 41, 20))
        self.label_Dinero.setObjectName("label_Dinero")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 531, 201))
        self.tableWidget.setStyleSheet("background:white;\n"
"color:black;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 100, 371, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_Ventas = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_Ventas.setCheckable(True)
        self.radio_Ventas.setChecked(True)
        self.radio_Ventas.setObjectName("radio_Ventas")
        self.horizontalLayout.addWidget(self.radio_Ventas)
        self.radio_Cuentas = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_Cuentas.setCheckable(True)
        self.radio_Cuentas.setObjectName("radio_Cuentas")
        self.horizontalLayout.addWidget(self.radio_Cuentas)
        self.radio_Producto = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_Producto.setCheckable(True)
        self.radio_Producto.setObjectName("radio_Producto")
        self.horizontalLayout.addWidget(self.radio_Producto)
        self.radio_Gasto = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radio_Gasto.setCheckable(True)
        self.radio_Gasto.setObjectName("radio_Gasto")
        self.horizontalLayout.addWidget(self.radio_Gasto)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(350, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form_Main)
        QtCore.QMetaObject.connectSlotsByName(Form_Main)

    def retranslateUi(self, Form_Main):
        _translate = QtCore.QCoreApplication.translate
        Form_Main.setWindowTitle(_translate("Form_Main", "Form"))
        self.groupBox.setTitle(_translate("Form_Main", "Opc"))
        self.btn_Venta.setText(_translate("Form_Main", "Venta"))
        self.btn_Producto.setText(_translate("Form_Main", "Producto"))
        self.btn_Cuenta.setText(_translate("Form_Main", "Cuenta"))
        self.btn_Gasto.setText(_translate("Form_Main", "Gasto"))
        self.label.setText(_translate("Form_Main", "Que operacion deceas hacer?..."))
        self.label_2.setText(_translate("Form_Main", "Que Deceas Visualizar ?..."))
        self.label_3.setText(_translate("Form_Main", "Ventas de HOY      $"))
        self.label_Dinero.setText(_translate("Form_Main", "       0"))
        self.radio_Ventas.setText(_translate("Form_Main", "Ventas"))
        self.radio_Cuentas.setText(_translate("Form_Main", "Cuentas"))
        self.radio_Producto.setText(_translate("Form_Main", "Producto"))
        self.radio_Gasto.setText(_translate("Form_Main", "Gastos"))
        self.pushButton.setText(_translate("Form_Main", "clear"))
        self.pushButton_2.setText(_translate("Form_Main", "Refreshc"))
