# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cuenta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Cuenta(object):
    def setupUi(self, Form_Cuenta):
        Form_Cuenta.setObjectName("Form_Cuenta")
        Form_Cuenta.resize(550, 300)
        Form_Cuenta.setMinimumSize(QtCore.QSize(550, 300))
        Form_Cuenta.setMaximumSize(QtCore.QSize(550, 300))
        Form_Cuenta.setStyleSheet("QWidget{\n"
"background:rgb(42, 42, 42);\n"
"font: 75 italic 12pt \"Arial Narrow\";\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton{\n"
"background:rgb(0, 127, 21);\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form_Cuenta)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form_Cuenta)
        self.groupBox.setMinimumSize(QtCore.QSize(529, 287))
        self.groupBox.setMaximumSize(QtCore.QSize(550, 300))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setMinimumSize(QtCore.QSize(400, 210))
        self.frame.setMaximumSize(QtCore.QSize(400, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_ok = QtWidgets.QPushButton(self.frame)
        self.btn_ok.setGeometry(QtCore.QRect(310, 210, 75, 23))
        self.btn_ok.setObjectName("btn_ok")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(-10, 0, 420, 170))
        self.tableWidget.setMinimumSize(QtCore.QSize(420, 170))
        self.tableWidget.setMaximumSize(QtCore.QSize(420, 160))
        self.tableWidget.setStyleSheet("background:white;\n"
"color:black;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 180, 101, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 170, 111, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_Nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_Nombre.setMaxLength(8)
        self.line_Nombre.setClearButtonEnabled(True)
        self.line_Nombre.setObjectName("line_Nombre")
        self.verticalLayout_2.addWidget(self.line_Nombre)
        self.line_cantidad = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_cantidad.setMaxLength(5)
        self.line_cantidad.setClearButtonEnabled(True)
        self.line_cantidad.setObjectName("line_cantidad")
        self.verticalLayout_2.addWidget(self.line_cantidad)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form_Cuenta)
        QtCore.QMetaObject.connectSlotsByName(Form_Cuenta)

    def retranslateUi(self, Form_Cuenta):
        _translate = QtCore.QCoreApplication.translate
        Form_Cuenta.setWindowTitle(_translate("Form_Cuenta", "Form"))
        self.groupBox.setTitle(_translate("Form_Cuenta", "Cuenta"))
        self.btn_ok.setText(_translate("Form_Cuenta", "ok"))
        self.label.setText(_translate("Form_Cuenta", "Cliente:  "))
        self.label_2.setText(_translate("Form_Cuenta", "Acuenta  :   "))
        self.line_Nombre.setPlaceholderText(_translate("Form_Cuenta", "Nombre"))
        self.line_cantidad.setPlaceholderText(_translate("Form_Cuenta", "$0000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Cuenta = QtWidgets.QWidget()
    ui = Ui_Form_Cuenta()
    ui.setupUi(Form_Cuenta)
    Form_Cuenta.show()
    sys.exit(app.exec_())
