# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gasto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Gasto(object):
    def setupUi(self, Form_Gasto):
        Form_Gasto.setObjectName("Form_Gasto")
        Form_Gasto.resize(320, 209)
        Form_Gasto.setMinimumSize(QtCore.QSize(200, 150))
        Form_Gasto.setMaximumSize(QtCore.QSize(320, 209))
        Form_Gasto.setStyleSheet("QWidget{\n"
"background:rgb(42, 42, 42);\n"
"font: 75 italic 12pt \"Arial Narrow\";\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton{\n"
"background:rgb(0, 127, 21);\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form_Gasto)
        self.gridLayout_2.setContentsMargins(0, 9, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form_Gasto)
        self.groupBox.setMinimumSize(QtCore.QSize(320, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(320, 200))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineNombre = QtWidgets.QLineEdit(self.frame)
        self.lineNombre.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineNombre.setMaxLength(35)
        self.lineNombre.setClearButtonEnabled(True)
        self.lineNombre.setObjectName("lineNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineNombre)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textDescripcion = QtWidgets.QTextEdit(self.frame)
        self.textDescripcion.setMaximumSize(QtCore.QSize(200, 100))
        self.textDescripcion.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textDescripcion.setStyleSheet("")
        self.textDescripcion.setObjectName("textDescripcion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textDescripcion)
        self.btnOk = QtWidgets.QPushButton(self.frame)
        self.btnOk.setObjectName("btnOk")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnOk)
        self.lineCosto = QtWidgets.QLineEdit(self.frame)
        self.lineCosto.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineCosto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineCosto.setMaxLength(5)
        self.lineCosto.setClearButtonEnabled(True)
        self.lineCosto.setObjectName("lineCosto")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineCosto)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form_Gasto)
        QtCore.QMetaObject.connectSlotsByName(Form_Gasto)

    def retranslateUi(self, Form_Gasto):
        _translate = QtCore.QCoreApplication.translate
        Form_Gasto.setWindowTitle(_translate("Form_Gasto", "Form"))
        self.groupBox.setTitle(_translate("Form_Gasto", "Gastos"))
        self.label.setText(_translate("Form_Gasto", "Nombre : "))
        self.lineNombre.setPlaceholderText(_translate("Form_Gasto", "Ejm: Gasolina"))
        self.label_4.setText(_translate("Form_Gasto", "Costo:    $"))
        self.label_3.setText(_translate("Form_Gasto", "Descripcion : "))
        self.textDescripcion.setPlaceholderText(_translate("Form_Gasto", "por que se hizo el gasto...."))
        self.btnOk.setText(_translate("Form_Gasto", "ok"))
        self.lineCosto.setPlaceholderText(_translate("Form_Gasto", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Gasto = QtWidgets.QWidget()
    ui = Ui_Form_Gasto()
    ui.setupUi(Form_Gasto)
    Form_Gasto.show()
    sys.exit(app.exec_())
