# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Producto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Producto(object):
    def setupUi(self, Form_Producto):
        Form_Producto.setObjectName("Form_Producto")
        Form_Producto.resize(180, 172)
        Form_Producto.setMinimumSize(QtCore.QSize(180, 172))
        Form_Producto.setMaximumSize(QtCore.QSize(180, 172))
        Form_Producto.setStyleSheet("QWidget{\n"
"background:rgb(42, 42, 42);\n"
"font: 75 italic 12pt \"Arial Narrow\";\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton{\n"
"background:rgb(0, 127, 21);\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form_Producto)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form_Producto)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 172))
        self.groupBox.setMaximumSize(QtCore.QSize(180, 172))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_3.setMaxLength(2)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setMaxLength(3)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.gridLayout_3.addWidget(self.frame, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form_Producto)
        QtCore.QMetaObject.connectSlotsByName(Form_Producto)

    def retranslateUi(self, Form_Producto):
        _translate = QtCore.QCoreApplication.translate
        Form_Producto.setWindowTitle(_translate("Form_Producto", "Form"))
        self.groupBox.setTitle(_translate("Form_Producto", "Producto"))
        self.label.setText(_translate("Form_Producto", "Numero:"))
        self.lineEdit_3.setPlaceholderText(_translate("Form_Producto", "socio"))
        self.label_2.setText(_translate("Form_Producto", "Tripa"))
        self.lineEdit_2.setPlaceholderText(_translate("Form_Producto", "0"))
        self.label_3.setText(_translate("Form_Producto", "Corazon"))
        self.lineEdit.setPlaceholderText(_translate("Form_Producto", "0"))
        self.pushButton.setText(_translate("Form_Producto", "ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Producto = QtWidgets.QWidget()
    ui = Ui_Form_Producto()
    ui.setupUi(Form_Producto)
    Form_Producto.show()
    sys.exit(app.exec_())
