# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Ventas(object):
    def setupUi(self, Form_Ventas):
        Form_Ventas.setObjectName("Form_Ventas")
        Form_Ventas.resize(418, 330)
        Form_Ventas.setMinimumSize(QtCore.QSize(418, 330))
        Form_Ventas.setMaximumSize(QtCore.QSize(418, 330))
        Form_Ventas.setStyleSheet("QWidget{\n"
"background:rgb(42, 42, 42);\n"
"font: 75 italic 12pt \"Arial Narrow\";\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton{\n"
"background:rgb(0, 127, 21);\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form_Ventas)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form_Ventas)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 300))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineCantidad = QtWidgets.QLineEdit(self.frame)
        self.lineCantidad.setMinimumSize(QtCore.QSize(100, 0))
        self.lineCantidad.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineCantidad.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineCantidad.setText("")
        self.lineCantidad.setMaxLength(5)
        self.lineCantidad.setClearButtonEnabled(True)
        self.lineCantidad.setObjectName("lineCantidad")
        self.gridLayout_2.addWidget(self.lineCantidad, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_Total = QtWidgets.QLabel(self.frame)
        self.label_Total.setObjectName("label_Total")
        self.gridLayout_2.addWidget(self.label_Total, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 2)
        self.radioCorazon = QtWidgets.QRadioButton(self.frame)
        self.radioCorazon.setObjectName("radioCorazon")
        self.gridLayout_2.addWidget(self.radioCorazon, 2, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.line_Recivo = QtWidgets.QLineEdit(self.frame)
        self.line_Recivo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.line_Recivo.setMaxLength(5)
        self.line_Recivo.setClearButtonEnabled(True)
        self.line_Recivo.setObjectName("line_Recivo")
        self.gridLayout_2.addWidget(self.line_Recivo, 6, 2, 1, 1)
        self.radioTripa = QtWidgets.QRadioButton(self.frame)
        self.radioTripa.setObjectName("radioTripa")
        self.gridLayout_2.addWidget(self.radioTripa, 2, 2, 1, 1)
        self.linePrecio = QtWidgets.QLineEdit(self.frame)
        self.linePrecio.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.linePrecio.setText("")
        self.linePrecio.setMaxLength(2)
        self.linePrecio.setClearButtonEnabled(True)
        self.linePrecio.setObjectName("linePrecio")
        self.gridLayout_2.addWidget(self.linePrecio, 4, 4, 1, 1)
        self.label_deuda = QtWidgets.QLabel(self.frame)
        self.label_deuda.setObjectName("label_deuda")
        self.gridLayout_2.addWidget(self.label_deuda, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_Cambio = QtWidgets.QLabel(self.frame)
        self.label_Cambio.setObjectName("label_Cambio")
        self.gridLayout_2.addWidget(self.label_Cambio, 7, 2, 1, 1)
        self.line_nombre = QtWidgets.QLineEdit(self.frame)
        self.line_nombre.setMaxLength(8)
        self.line_nombre.setClearButtonEnabled(True)
        self.line_nombre.setObjectName("line_nombre")
        self.gridLayout_2.addWidget(self.line_nombre, 0, 2, 1, 2)
        self.btnOk = QtWidgets.QPushButton(self.frame)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout_2.addWidget(self.btnOk, 7, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form_Ventas)
        QtCore.QMetaObject.connectSlotsByName(Form_Ventas)

    def retranslateUi(self, Form_Ventas):
        _translate = QtCore.QCoreApplication.translate
        Form_Ventas.setWindowTitle(_translate("Form_Ventas", "Form"))
        self.groupBox.setTitle(_translate("Form_Ventas", "Ventas"))
        self.lineCantidad.setPlaceholderText(_translate("Form_Ventas", "0"))
        self.label_10.setText(_translate("Form_Ventas", "Producto : "))
        self.label_7.setText(_translate("Form_Ventas", "Cliente : "))
        self.label_Total.setText(_translate("Form_Ventas", "0"))
        self.label_8.setText(_translate("Form_Ventas", "Cuenta Anterior: "))
        self.radioCorazon.setText(_translate("Form_Ventas", "Corazon"))
        self.label_5.setText(_translate("Form_Ventas", "Recivo :      $"))
        self.line_Recivo.setPlaceholderText(_translate("Form_Ventas", "0"))
        self.radioTripa.setText(_translate("Form_Ventas", "Tripa"))
        self.linePrecio.setPlaceholderText(_translate("Form_Ventas", "0"))
        self.label_deuda.setText(_translate("Form_Ventas", "0"))
        self.label_2.setText(_translate("Form_Ventas", "$"))
        self.label_3.setText(_translate("Form_Ventas", "Total  :"))
        self.label.setText(_translate("Form_Ventas", "Cantidad:  KG / Pz"))
        self.label_4.setText(_translate("Form_Ventas", "Cambio:    $"))
        self.label_Cambio.setText(_translate("Form_Ventas", "             0"))
        self.line_nombre.setPlaceholderText(_translate("Form_Ventas", "Nom Cliente"))
        self.btnOk.setText(_translate("Form_Ventas", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Ventas = QtWidgets.QWidget()
    ui = Ui_Form_Ventas()
    ui.setupUi(Form_Ventas)
    Form_Ventas.show()
    sys.exit(app.exec_())
